CFLAGS= -Wall -fpic -coverage -lm -std=c99

rngs.o: rngs.h rngs.c
	gcc -c rngs.c -g  $(CFLAGS)

dominion.o: dominion.h dominion.c rngs.o
	gcc -c dominion.c -g  $(CFLAGS)

playdom: dominion.o playdom.c
	gcc -o playdom playdom.c -g dominion.o rngs.o $(CFLAGS)
#To run playdom you need to entere: ./playdom <any integer number> like ./playdom 10*/
testDrawCard: testDrawCard.c dominion.o rngs.o
	gcc  -o testDrawCard -g  testDrawCard.c dominion.o rngs.o $(CFLAGS)

badTestDrawCard: badTestDrawCard.c dominion.o rngs.o
	gcc -o badTestDrawCard -g  badTestDrawCard.c dominion.o rngs.o $(CFLAGS)

testBuyCard: testDrawCard.c dominion.o rngs.o
	gcc -o testDrawCard -g  testDrawCard.c dominion.o rngs.o $(CFLAGS)

testAll: dominion.o testSuite.c
	gcc -o testSuite testSuite.c -g  dominion.o rngs.o $(CFLAGS)

interface.o: interface.h interface.c
	gcc -c interface.c -g  $(CFLAGS)

runtests: testDrawCard
	./testDrawCard &> unittestresult.out
	gcov dominion.c >> unittestresult.out
	cat dominion.c.gcov >> unittestresult.out

player: player.c interface.o
	gcc -o player player.c -g  dominion.o rngs.o interface.o $(CFLAGS)

unitTest1: unittest1.c dominion.o rngs.o
	gcc -o unittest1 -g unittest1.c unittest_helper.c dominion.o rngs.o $(CFLAGS)

unitTest2: unittest2.c dominion.o rngs.o
	gcc -o unittest2 -g unittest2.c unittest_helper.c dominion.o rngs.o $(CFLAGS)

unitTest3: unittest3.c dominion.o rngs.o
	gcc -o unittest3 -g unittest3.c unittest_helper.c dominion.o rngs.o $(CFLAGS)

unitTest4: unittest4.c dominion.o rngs.o
	gcc -o unittest4 -g unittest4.c unittest_helper.c dominion.o rngs.o $(CFLAGS)

unitTest5: unittest5.c dominion.o rngs.o
	gcc -o unittest5 -g unittest5.c unittest_helper.c dominion.o rngs.o $(CFLAGS)

runUnitTests: unitTest1 unitTest2 unitTest3 unitTest4 unitTest5
	./unittest1 >> unittestresults.out
	gcov -f dominion.c >> unittestresults.out
	#./unittest2 >> unittestresults.out
	#gcov dominion.c >> unittestresults.out
	#./unittest3 >> unittestresults.out
	#gcov dominion.c >> unittestresults.out
	#./unittest4 >> unittestresults.out
	#gcov dominion.c >> unittestresults.out
	#./unittest5 >> unittestresults.out
	#gcov dominion.c >> unittestresults.out

all: playdom player



clean:
	rm -f *.o playdom.exe playdom player player.exe  unittest1 unittest2 unittest3 unittest4 unittest5 *.gcov *.gcda *.gcno *.so *.out testDrawCard testDrawCard.exe
